server:
  port: 8080

logging:
  level:
    org.springframework.web: INFO

spring:
  application:
    name: device-registration-core
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: device_registration_service
        use_sql_comments: true
        format_sql: true
        criteria:
          literal_handling_mode: BIND
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/unit_techno?currentSchema=device_registration_service
    username: device_registration_admin
    password: squd
  eureka:
    client:
      serviceUrl:
        defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true

  cloud:
    config:
      discovery:
        enable: true
        service-id: device_registration_service